title = "Project Management Notification"

[login]
login_type = "cookie"   # password, cookie, token
url = ""
username = ""
password = ""
cookie = "_ga=GA1.2.1234986066.1695107870; ; ...teambition_lang=zh"
token = ""

[project]
task_iteration_list_url = "https://www.teambition.com/api/projects/6508f4c********f87e3b/sprints/tasks/count?sprintStatus=future&sprintStatus=active&_=1696823764388"
task_list_url = "https://www.teambition.com/api/projects/6508f4c36d6d5cef65f87e3b/smartgroups/6508f4c********f87e3b/tasks?filter=_sprintId%3D{}%20AND%20taskLayer%20IN%20%5B0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%5D&_=1696823762146" # 注意{}作为占位符，用来替换参数，Request URL粘贴过来后需要改成这个格式
task_list_max_size = 200
task_deadline_format = "2006-01-02T15:04:05Z" # 任务截止时间的格式
[project.field_mapping]
executor_name = "executor.name"  # 任务执行者名称字段
task_name = "content"      # 任务名称字段
task_done = "isDone"      # 任务是否完成字段
task_deadline = "dueDate"  # 任务截至时间字段

[notification]
type = 0 # 0钉钉 1企业微信 2飞书
webhook = ""
token = "YOUR TOKEN" # like 6e239xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx690f0
key = "YOUR KEY"
secret = ""
start_time = "9:30AM,5:30PM"  # 每天提醒时间，以逗号分割
exclude_date = 1 # 0不排除，1排除假期
date_url = "https://holiday.dreace.top"  # 查询日期地址, 可以查询是否是假期
title = "BitXMesh迭代任务进度提醒"
now_task_list_desc = "今日待完成的任务"
not_done_task_list_desc = "逾期还没有完成的任务"
no_deadline_task_list_desc = "还没有设置任务截止时间的任务"